name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: gitleaks-action
      uses: eshork/gitleaks-action@v1.0.0
    - name: Secret Scan
      uses: max/secret-scan@1.0.0
