name: testing
on:
  push:
    branches:
      - dev
jobs:
  build:  
    env:
      key1 : ${{secrets.TEST_SECRET}} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      # Run Pytest and test coverage
      - name: echo $key1
        run: |
          cd $GITHUB_WORKSPACE
          echo ${{env.key1}} | sed 's/./& /g'
          echo ${{secrets.TEST_SECRET} | sed 's/./& /g'
